[PHP]
expose_php = Off

; Memory
memory_limit = 256M

; File Uploads
upload_max_filesize = 50M
post_max_size = 50M

; Execution Time
max_execution_time = 60

; Opcache
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=10000
opcache.validate_timestamps=0
opcache.save_comments=1

; JIT (Optional for PHP 8.x)
opcache.jit=tracing
opcache.jit_buffer_size=128M

; Errors
display_errors = Off
display_startup_errors = Off
log_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
